micronaut:
  application:
    name: micronautRestApi
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:h2:mem:dev;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'com.example.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update